# Generated by Django 5.1.4 on 2025-01-16 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('vendor', '0004_vendorpayment_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient_vendor',
        ),
        migrations.AddField(
            model_name='message',
            name='recipient_vendors',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to='vendor.vendor'),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(blank=True, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
