# Generated by Django 5.1.4 on 2025-01-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_recipient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='recipient_vendors',
        ),
    ]
