# Generated by Django 5.1.4 on 2025-01-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='vendor_fee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
