# Generated by Django 5.1.4 on 2025-01-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactionitem_vendor_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='sold_by',
            field=models.CharField(default='', max_length=255),
        ),
    ]
