# Generated by Django 5.1.4 on 2025-01-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_transactionitem_sold_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionitem',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
