# Generated by Django 5.1.4 on 2025-01-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactionitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card_fee',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
