version: "3.8"

services:
  api:
    container_name: helen_underground_v2
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
